### Exercícios - Capítulo 5 - Parte 3

In [59]:
import pandas as pd
import numpy as np

# Carregar dataset
paises = pd.read_csv('paises.csv', delimiter=';')

# Mostrar colunas
print(paises.columns)

Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='object')

1. Carregue o Dataset paises.csv e em seguida mostre: 

    a.Quais são os países da OCEANIA; 

    b.Quantos países são da OCEANIA; 
    
Dica: para busca de padrões textuais no Pandas, use métodos da subclasse str da Series. Ex: series.str.contains(‘texto’)

In [60]:
# Separar países da Oceania
oceania = paises[paises['Region'].str.contains('OCEANIA')]

# Mostrar quais são os países da Oceania
print('Os países da Oceania são:')
print(oceania['Country'].values)

# Mostrar quantos países são da Oceania
print(f"São {len(oceania)} países da Oceania.")

Os países da Oceania são:
['American Samoa ' 'Australia ' 'Cook Islands ' 'Fiji '
 'French Polynesia ' 'Guam ' 'Kiribati ' 'Marshall Islands '
 'Micronesia, Fed. St. ' 'Nauru ' 'New Caledonia ' 'New Zealand '
 'N. Mariana Islands ' 'Palau ' 'Papua New Guinea ' 'Samoa '
 'Solomon Islands ' 'Tonga ' 'Tuvalu ' 'Vanuatu ' 'Wallis and Futuna ']
São 21 países da Oceania.

2. Encontre o nome e a região do país que possui a maior população segundo este Dataset;

In [61]:
# Separar país com a maior população
maiorPopulacao = paises.nlargest(1, 'Population')

# Mostrar nome e região desse país
print(f"O país com maior população é {maiorPopulacao['Country'].item()}, que está na região {maiorPopulacao['Region'].item()}.")

O país com maior população é China , que está na região ASIA (EX. NEAR EAST)         .

3. Agrupe os países por Regiões. Em seguida, mostre a média de alfabetização (Literacy (%)) de cada região do planeta;

In [62]:
# Agrupar países por regiões
regioes = paises.groupby('Region')

# Calcular e mostrar média de alfabetização de cada região
qtdPaises = regioes.count()['Country'] #qtd paises por região
somaAlf = regioes.sum()['Literacy (%)'] #soma da alfabetização
mediaAlf = somaAlf/qtdPaises

print(mediaAlf)

Region
ASIA (EX. NEAR EAST)                   79.553571
BALTICS                                99.733333
C.W. OF IND. STATES                    98.725000
EASTERN EUROPE                         72.816667
LATIN AMER. & CARIB                    88.640000
NEAR EAST                              69.581250
NORTHERN AFRICA                        56.033333
NORTHERN AMERICA                       78.200000
OCEANIA                                71.914286
SUB-SAHARAN AFRICA                     61.284314
WESTERN EUROPE                         80.821429
dtype: float64

4.  Busque o nome de todos os países do Dataset que não possuem costa marítima (Coastline (coast/area ratio) == 0) e guarde-os em um novo arquivo chamado noCoast.csv;

In [63]:
# Separar países que não possuem costa marítima
semCostaMaritima = paises['Country'][paises['Coastline (coast/area ratio)'] == 0]

# Salvar em um arquivo
semCostaMaritima.to_csv('noCoast.csv', sep=';')

5. Faça uma função que receba a taxa de mortalidade de cada país (Deathrate) e retorne o texto ‘Balanced’ caso o valor seja < 9 e ‘Urgent’ caso contrário. Em seguida, crie um campo no Dataset chamado ‘Humanitarian Help’ que receba estes valores para cada país. No final, mostre o Dataset para verificar se a inserção da nova coluna foi feita com sucesso.

In [64]:
# Criar função para verificação do nível da taxa de mortalidade
def humanitarianHelp(x):
    if x<9:
        return 'Balanced'
    else:
        return 'Urgent'
    
# Criar nova coluna no dataset com dados dessa verificação
paises['Humanitarian Help'] = paises['Deathrate'].apply(humanitarianHelp)

# Mostrar 10 primeiros itens do dataset
paises.head(10)

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),...,Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service,Humanitarian Help
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700,36.0,...,12.13,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380,Urgent
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500,86.5,...,21.09,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579,Balanced
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000,70.0,...,3.22,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298,Balanced
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000,97.0,...,10.00,15.00,75.00,2.0,22.46,3.27,0.000,0.000,0.000,Balanced
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000,100.0,...,2.22,0.00,97.78,3.0,8.71,6.25,0.000,0.000,0.000,Balanced
5,Angola,SUB-SAHARAN AFRICA,12127071,1246700,9.7,0.13,0.00,191.19,1900,42.0,...,2.41,0.24,97.35,0.0,45.11,24.20,0.096,0.658,0.246,Urgent
6,Anguilla,LATIN AMER. & CARIB,13477,102,132.1,59.80,10.76,21.03,8600,95.0,...,0.00,0.00,100.00,2.0,14.17,5.34,0.040,0.180,0.780,Balanced
7,Antigua & Barbuda,LATIN AMER. & CARIB,69108,443,156.0,34.54,-6.15,19.46,11000,89.0,...,18.18,4.55,77.27,2.0,16.93,5.37,0.038,0.220,0.743,Balanced
8,Argentina,LATIN AMER. & CARIB,39921833,2766890,14.4,0.18,0.61,15.18,11200,97.1,...,12.31,0.48,87.21,3.0,16.73,7.55,0.095,0.358,0.547,Balanced
9,Armenia,C.W. OF IND. STATES,2976372,29800,99.9,0.00,-6.47,23.28,3500,98.6,...,17.55,2.30,80.15,4.0,12.07,8.23,0.239,0.343,0.418,Balanced